apiVersion: apps/v1
kind: Deployment
metadata:
  name: agrius-jaws-deployment
  labels:
    app: agrius-jaws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agrius-jaws
  template:
    metadata:
      labels:
        app: agrius-jaws
    spec:
      containers:
      - name: agrius-jaws
        image: nandanrao/agrius-jaws
        resources:
          requests:
            cpu: "750m"
            memory: "1536Mi"
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: agrius-jaws-envs
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "keys/key.json"
        - name: GOOGLE_PROJECT_ID
          value: "toixotoixo"
        - name: JAWS_TOPIC
          value: "agrius-test"
        - name: JAWS_SHEET_ID
          value: "1tTdi29asCLDT5uWxdhvizOhP6wVT-Y0HtAS9bsxizdY"
        - name: JAWS_REFRESH_INTERVAL
          value: "30"
        - name: T_QUEUE_SIZE
          value: "250000"
        - name: T_THREADS
          value: "4"
        - name: JVM_OPTS
          value: "-Xms512M -Xmx2048M"
        volumeMounts:
            - name: keys
              mountPath: /usr/src/app/keys
              readOnly: true
      volumes:
        - name: keys
          secret:
            secretName: agrius-jaws-keys
