apiVersion: apps/v1
kind: Deployment
metadata:
  name: agrius-jaws-deployment
  labels:
    app: agrius-jaws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agrius-jaws
  template:
    metadata:
      labels:
        app: agrius-jaws
    spec:
      containers:
      - name: agrius-jaws
        image: nandanrao/agrius-jaws
        resources:
          requests:
            cpu: "100m"
            memory: "384Mi"
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: agrius-jaws-envs
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "keys/key.json"
        - name: GOOGLE_PROJECT_ID
          value: "toixotoixo"
        - name: JAWS_TOPIC
          value: "agrius-india"
        - name: JAWS_SHEET_ID
          value: "1tTdi29asCLDT5uWxdhvizOhP6wVT-Y0HtAS9bsxizdY"
        - name: JAWS_REFRESH_INTERVAL
          value: "20"
        - name: T_QUEUE_SIZE
          value: "1000000" # should test sizes here
        - name: T_THREADS
          value: "100"
        - name: JVM_OPTS
          value: "-Xms384M -Xmx2048M"
        volumeMounts:
            - name: keys
              mountPath: /usr/src/app/keys
              readOnly: true
      volumes:
        - name: keys
          secret:
            secretName: agrius-jaws-keys
