apiVersion: apps/v1
kind: Deployment
metadata:
  name: agrius-jaws-deployment
  labels:
    app: agrius-jaws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agrius-jaws
  template:
    metadata:
      labels:
        app: agrius-jaws
    spec:
      containers:
      - name: agrius-jaws
        image: nandanrao/agrius-jaws
        resources:
          requests:
            cpu: "1000m"
            memory: "2048Mi"
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: agrius-jaws-envs
        env:
        - name: JVM_OPTS
          value: "-Xms512M -Xmx2048M"
        volumeMounts:
            - name: keys
              mountPath: /usr/src/app/keys
              readOnly: true
      volumes:
        - name: keys
          secret:
            secretName: agrius-jaws-keys
