apiVersion: apps/v1
kind: Deployment
metadata:
  name: agrius-jaws-deployment
  labels:
    app: agrius-jaws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agrius-jaws
  template:
    metadata:
      labels:
        app: agrius-jaws
    spec:
      containers:
      - name: agrius-jaws
        image: nandanrao/agrius-jaws:0.0.10
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: agrius-jaws-envs
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "keys/key.json"
        - name: GOOGLE_PROJECT_ID
          value: "toixotoixo"
        - name: JAWS_TOPIC
          value: "agrius-india"
        - name: JAWS_SHEET_ID
          value: "1LzH7sHJX6WnFTpTIeSsNV1J_ep61SpugZY_SVQoSDjg"
        - name: JAWS_SHEET_USERS
          value: "follows!A2:A"
        - name: JAWS_SHEET_HASHTAGS
          value: "follows!F2:F,follows!G2:G"
        - name: JAWS_SHEET_URLS
          value: "follows!E2:E"
        - name: JAWS_REFRESH_INTERVAL
          value: "30"
        - name: T_QUEUE_SIZE
          value: "1000000"
        - name: T_THREADS
          value: "100"
        - name: JAVA_TOOL_OPTIONS
          value: "-Xms256m -Xmx1024m -XX:MaxGCPauseMillis=1000"
        volumeMounts:
            - name: keys
              mountPath: /usr/src/app/keys
              readOnly: true
      volumes:
        - name: keys
          secret:
            secretName: agrius-jaws-keys
